httpRoute:
  enabled: true
  hostnames:
    - genius-core-admin.dev-kosm-core.dev.verses.build
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: dev-kosm-core-gateway
      namespace: istio-system
      sectionName: https-playground-wildcard
  rules:
    - matches:
        - headers:
            - type: Exact
              name: host
              value: genius-core-admin.dev-kosm-core.dev.verses.build
          path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: '{{ include "genius-core-admin.fullname" . }}'
          port: '{{ .Values.service.port }}'
extraObjects:
  - |-
    apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: "{{ include "genius-core-admin.fullname" . }}-env-config"
      namespace: {{ .Release.Namespace | quote }}
      labels:
        {{- include "genius-core-admin.labels" . | nindent 4 }}
    spec:
      secretStoreRef:
        name: application-store
        kind: ClusterSecretStore
      refreshInterval: 30m
      target:
        name: "{{ include "genius-core-admin.fullname" . }}-env-config"
        creationPolicy: Owner
        template:
          engineVersion: v2
          data:
            .env.production: |-
              NEXT_PUBLIC_APP_GENIUS_DB_URL='http://genius-core:50052'
              UNLEASH_SERVER_API_URL=''
              UNLEASH_SERVER_API_TOKEN=''
              NEXT_PUBLIC_UNLEASH_SERVER_API_URL=''
              NEXT_PUBLIC_UNLEASH_FRONTEND_API_TOKEN=''
              SENTRY_AUTH_TOKEN=''
              AUTH_URL={{ printf "https://%s/api/auth" .Values.externalDomain | squote }}
              AUTH_SECRET={{`'{{ .authSessionCookieSecret }}'`}}
              CLIENT_ID='RC639CiCXuhcDLe4y3NfCC1FwyDsRkBr'
              CLIENT_SECRET={{`'{{ .authClientSecret }}'`}}
              ISSUER_BASE_URL='https://kosm-dev-verses.us.auth0.com'
              AUDIENCE='https://kosm-dev-verses.us.auth0.com/api/v2/'
              AUTH_SCOPE='openid profile email'
      data:
        - secretKey: unleashServerApiToken
          remoteRef:
            key: sandbox/genius-core-admin/dev/unleash-server-api-token
            property: token
        - secretKey: auth0SessionCookieSecret
          remoteRef:
            key: sandbox/genius-core-admin/dev/auth0-session-cookie-secret
            property: sessionCookieSecret
        - secretKey: auth0ClientSecret
          remoteRef:
            key: sandbox/genius-core-admin/dev/auth0-client-secret
            property: clientSecret
        - secretKey: sentryAuthToken
          remoteRef:
            key: sandbox/genius-core-admin/dev/sentry-auth-token
            property: authToken
        - secretKey: auth0M2mAppClientSecret
          remoteRef:
            key: sandbox/genius-core-admin/dev/auth0-m2m-app-client-secret
            property: clientSecret
        - secretKey: authSessionCookieSecret
          remoteRef:
            key: sandbox/genius-core-admin/dev/auth/auth0/session-cookie-secret
            property: sessionCookieSecret
        - secretKey: authClientSecret
          remoteRef:
            key: sandbox/genius-core-admin/dev/auth/auth0/client-secret
            property: clientSecret
