apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genius-core-admin.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "genius-core-admin.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "genius-core-admin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/env-config: {{ include (print $.Template.BasePath "/secret-env-config.yaml") . | sha256sum | quote }}
        {{- with .Values.podAnnotations }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      labels:
        {{- include "genius-core-admin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "genius-core-admin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: env-config
              mountPath: /app/run/.env.production
              subPath: .env.production
              readOnly: true
      volumes:
        - name: env-config
          secret:
            {{- if .Values.configExistingSecret.name }}
            secretName: {{ .Values.configExistingSecret.name | quote }}
            {{- else if .Values.config }}
            secretName: "{{ include "genius-core-admin.fullname" . }}-env-config"            
            {{- end }}
            defaultMode: 0400
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
