{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "genius-core-admin.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "genius-core-admin.labels" . | nindent 4 }}
{{- end }}
