{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "genius-core.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "genius-core.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{ toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    {{ tpl (toYaml .Values.httpRoute.hostnames) . | nindent 4 }}
  rules:
    {{ tpl (toYaml .Values.httpRoute.rules) . | nindent 4 }}
{{- end }}
