{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "genius-core.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "genius-core.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "genius-core.selectorLabels" . | nindent 6 }}
{{- end }}
