apiVersion: v1
kind: Service
metadata:
  name: {{ include "genius-core.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "genius-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.ports.ws }}
      targetPort: http-ws
      protocol: TCP
      name: http-ws
  selector:
    {{- include "genius-core.selectorLabels" . | nindent 4 }}
