name: Test Charts in K3S

on:
  push:
    branches:
      - main

jobs:
  create-k3s-cluster:
    name: Start k3s cluster
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k3s-version:
          - "1.30"
        include:
          - k3s-version: "1.30"
            image-tag: v1.30.0-k3s1
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Start k3s server
        uses: addnab/docker-run-action@v3
        with:
          image: rancher/k3s:${{ matrix.image-tag }}
          options: >-
            --name k3s-server
            --hostname k3s-server
            --privileged
            -p 6443:6443
            -v ${{ github.workspace }}/.github/workflows/k3s/config.yaml:/etc/rancher/k3s/config.yaml.d/00-github-actions-ci.yaml
            -d
          run: |-
            /bin/k3s server
      
      - name: Download wait-for-it
        run: |-
          curl -fSsLO https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x ./wait-for-it.sh
      
      - name: Wait for k3s server
        run: |-
          ./wait-for-it.sh localhost:6443 --strict --timeout=120 -- echo "k3s server is up"

      - name: Copy kubeconfig from k3s server to workspace
        run: |-
          mkdir -p "${HOME}/.kube/"
          until docker cp k3s-server:/etc/rancher/k3s/k3s.yaml "${HOME}/.kube/config"
          do
            echo "Waiting for kubeconfig to be generated..."
          done

      - name: Run kubectl
        run: |-
          kubectl version
